esphome:
  name: wemos-4-retencka

esp8266:
  #board: d1_mini_pro
  #board: d1_mini
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_base64_key
  
ota:
  platform: esphome
  password: !secret ota_password
  
wifi:
  ssid: !secret wifi_name
  password: !secret wifi_password
  #  use_address: wemos-4-test.local

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Wemos-4-Retencka"
    password: !secret ap_password

captive_portal:

# required for Dallas sensor
one_wire:
  - platform: gpio
    pin: GPIO14 #D5

sensor:
  - platform: dallas_temp
    #address: 0x1234567812345628 #Required if there is more than one device on the bus.
    update_interval: 120s
    name: "Teplota v retenčce"
    filters:
      - offset: 0.5
      - filter_out: -50

  - platform: ultrasonic
    trigger_pin: GPIO04   # D2
    echo_pin: GPIO05      # D1
    name: "Výška hladiny v retenčce"
    id: vyska_hladiny_v_retencce
    filters:
      - offset: -1.4      # průměr nádrže - vzdálenost senzoru ode dna
      - multiply: -1
      - filter_out: nan   # filtrování nulových hodnot
      - median:
          window_size: 10
          send_every: 2
    update_interval: 120s
    unit_of_measurement: "m"

  # Derived sensors configuration (calculated from vyska_hladiny_v_retencce)
  - platform: template
    name: "Objem vody v retenčce v litrech"
    id: objem_vody_litry
    update_interval: 120s
    # délka nádrže = 4,2m ; poloměr nádrže = 0,7m
    lambda: |-
      float x = id(vyska_hladiny_v_retencce).state;
      if (isnan(x)) return 0;
      float calculated = 1000 * 4.2 * (0.7 * 0.7 * acos((0.7 - x) / 0.7) - (0.7 - x) * sqrt((2 * x * 0.7) - (x * x)));
      return calculated;
    filters:
      - filter_out: nan       # filtrování nulových hodnot
      - median:
          window_size: 10
          send_every: 2
    unit_of_measurement: "l"
    accuracy_decimals: 0

  - platform: template
    name: "Objem vody v retenčce v procentech"
    id: objem_vody_procenta
    update_interval: 120s
    # délka nádrže = 4,2m ; poloměr nádrže = 0,7m ; reálná max. výška hladiny 1.14 m -> 5638 litrů
    lambda: |-
      float x = id(vyska_hladiny_v_retencce).state;
      if (isnan(x)) return 0;
      float calculated = 100 * (1000 * 4.2 * (0.7 * 0.7 * acos((0.7 - x) / 0.7) - (0.7 - x) * sqrt((2 * x * 0.7) - (x * x))) / 5638);
      return calculated;
    filters:
      - filter_out: nan       # filtrování nulových hodnot
      - median:
          window_size: 10
          send_every: 2
    unit_of_measurement: "%"
    accuracy_decimals: 0

#  - platform: template
#    name: "Úhrn srážek za hodinu"
#    id: srazky
#    unit_of_measurement: 'mm'
#   value_template: {{ float(states('sensor.naprselo_za_posledni_hodinu)) / 183 }}

web_server:
  port: 80
